[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I"]
ignore = ["E501"]

exclude = [
  "app/api/**",
  "app/agent/**",
  "app/main.py",
]

[tool.mypy]
python_version = "3.11"
disallow_untyped_defs = false
check_untyped_defs = true